/**
 * Build the icon marks from Phosphor.
 *
 * **Why a generator and not a table somebody pasted.** The marks used to be
 * hand-drawn here — 32 stroke paths on a 24×24 grid, written by whoever needed
 * one — and the household's verdict was that the icons suck. They were right,
 * and it is not a fixable kind of wrong: drawing a legible 24px glyph is a
 * craft, and a client that hand-rolls its own icon family is doing badly, by
 * hand, a job a professional family has already done.
 *
 * Phosphor is the family the client this replaces uses, so the household
 * already knows these shapes. It arrives as SVG, which is what this wants —
 * a font would mean a download, a flash of nothing, and a glyph that cannot be
 * two colours. The paths are inlined into `marks.ts` at build time, so at
 * runtime there is no dependency at all.
 *
 * Re-run with `node tool/icons.mjs` after changing the table below.
 *
 * Phosphor Icons is MIT licensed — see `src/design/PHOSPHOR-LICENSE`.
 */
import { readFileSync, writeFileSync, copyFileSync } from 'node:fs';
import { join } from 'node:path';

const SET = 'node_modules/@phosphor-icons/core/assets';

/**
 * Our mark names, and the Phosphor icon each is drawn with.
 *
 * The left column is this client's vocabulary (§11.2 resolves a device to one
 * of these); the right is the drawing. Keeping the two apart is what lets the
 * family change without touching a single resolution rule.
 */
const MARKS = {
  light: 'lightbulb',
  switch: 'toggle-right',
  outlet: 'plug',
  fan: 'fan',
  lock: 'lock',
  door: 'door',
  window: 'app-window',
  garage: 'garage',
  motion: 'person-simple-walk',
  temperature: 'thermometer-simple',
  water: 'drop',
  rain: 'cloud-rain',
  lightning: 'lightning',
  vibration: 'vibrate',
  weather: 'cloud-sun',
  media: 'television-simple',
  speaker: 'speaker-hifi',
  scene: 'sparkle',
  remote: 'numpad',
  timer: 'timer',
  hub: 'broadcast',
  battery: 'battery-high',
  device: 'circuitry',
  play: 'play',
  pause: 'pause',
  play_pause: 'play-pause',
  stop: 'stop',
  prev: 'skip-back',
  next: 'skip-forward',
  volume_up: 'speaker-high',
  volume_down: 'speaker-low',
  mute: 'speaker-slash',
};

/**
 * The marks that get a filled twin, for a device that is on.
 *
 * **The state a row is in should be readable without reading it.** An outlet
 * that is on and one that is off drew the identical grey glyph, and the only
 * difference on the row was the toggle at the far end — so a column of five
 * plugs took five separate looks. Phosphor ships the same drawing in a filled
 * weight, which is the difference a glance can use.
 *
 * Only where "on" means something. A thermometer is not on.
 */
const FILLED = [
  'light',
  'switch',
  'outlet',
  'fan',
  'lock',
  'door',
  'window',
  'garage',
  'motion',
  'media',
  'speaker',
  'scene',
];

/** The drawing inside the `<svg>`, which is all we keep. */
function inner(weight, name) {
  const file = join(SET, weight, weight === 'regular' ? `${name}.svg` : `${name}-${weight}.svg`);
  const svg = readFileSync(file, 'utf8');
  const body = svg.replace(/^[\s\S]*?<svg[^>]*>/, '').replace(/<\/svg>\s*$/, '');
  // Phosphor states `fill="currentColor"` on the root, which we re-state once
  // in `icon()` rather than on every path.
  return body.replace(/\s*fill="[^"]*"/g, '').trim();
}

const lines = [];
for (const [mark, name] of Object.entries(MARKS)) {
  lines.push(`  ${JSON.stringify(mark)}: ${JSON.stringify(inner('regular', name))},`);
}
const filled = [];
for (const mark of FILLED) {
  filled.push(`  ${JSON.stringify(mark)}: ${JSON.stringify(inner('fill', MARKS[mark]))},`);
}

const out = `/**
 * The icon marks, drawn by Phosphor.
 *
 * **Generated by \`tool/icons.mjs\` — do not edit.** Change the table there and
 * re-run it. The name on the left is this client's vocabulary (§11.2); the
 * drawing is Phosphor's, inlined so there is no runtime dependency and no font
 * to wait for.
 *
 * Phosphor Icons is MIT licensed — see \`PHOSPHOR-LICENSE\` beside this file.
 *
 * On a 256×256 grid and filled, which is Phosphor's own geometry. The marks
 * before these were strokes on a 24×24 grid, so \`icon()\` states the viewBox
 * and the paint in one place rather than every caller restating it.
 */

/** The drawing for each mark, as inner SVG. */
export const MARKS: Record<string, string> = {
${lines.join('\n')}
};

/**
 * The same drawing, filled, for the marks where being on means something.
 *
 * A device that is on and one that is off drew the identical glyph, so a
 * column of five plugs took five separate looks to read. Absent for a mark
 * that has no on — a thermometer is not on — and \`icon()\` falls back to the
 * ordinary one.
 */
export const FILLED_MARKS: Record<string, string> = {
${filled.join('\n')}
};
`;

writeFileSync('src/design/marks.ts', out);
copyFileSync(join('node_modules/@phosphor-icons/core', 'LICENSE'), 'src/design/PHOSPHOR-LICENSE');
console.log(
  `marks.ts: ${Object.keys(MARKS).length} marks, ${filled.length} filled, ${out.length} bytes`,
);
