/**
 * Icons, derived from what a device declares (§11.2).
 *
 * **This is a presentation table, and it belongs here.** §1.1 forbids mapping
 * `device_type` to a *behaviour* — that is a client deciding what a plugin's
 * word means, closed against the next plugin and silently wrong rather than
 * visibly missing. A picture is the opposite case: it is presentation, the
 * core/client boundary puts presentation in the client (§1.2), and §11.2
 * already specifies the resolution order — a name rule, then `ui_hint`, then
 * `device_type`. An unknown type gets the generic device mark, which is a
 * visible "I don't know what this is", not a wrong claim about it.
 *
 * `ui_hint` outranks `device_type` because that is the field's whole purpose: a
 * switch a person hinted as a light *is* a light, and drawing it as a rocker
 * would make the override cosmetic.
 *
 * **The drawings are Phosphor's** (`design/marks.ts`, generated by
 * `tool/icons.mjs`). They were hand-drawn here first — 32 stroke paths on a
 * 24×24 grid, added by whoever needed one — and the household's verdict was
 * that the icons suck. That is not a fixable kind of wrong: drawing a legible
 * 24px glyph is a craft, and a client hand-rolling its own icon family is
 * doing badly, by hand, what a professional family has already done. Phosphor
 * is the family the client this replaces uses, so these are shapes the
 * household already knows.
 *
 * `currentColor` throughout, so one mark works on every skin and takes its
 * colour from whatever state the caller is painting.
 */
import { html, type TemplateResult } from 'lit';
import { unsafeSVG } from 'lit/directives/unsafe-svg.js';
import { FILLED_MARKS, MARKS } from './marks.js';

/** Declared word → mark. Presentation only; nothing behavioural reads this. */
const BY_WORD: Record<string, string> = {
  light: 'light',
  bulb: 'light',
  switch: 'switch',
  outlet: 'outlet',
  plug: 'outlet',
  fan: 'fan',
  lock: 'lock',
  door: 'door',
  contact_sensor: 'door',
  window: 'window',
  garage: 'garage',
  motion: 'motion',
  motion_sensor: 'motion',
  occupancy: 'motion',
  occupancy_sensor: 'motion',
  presence: 'motion',
  temperature: 'temperature',
  temperature_sensor: 'temperature',
  thermostat: 'temperature',
  climate: 'temperature',
  humidity: 'water',
  water: 'water',
  water_sensor: 'water',
  leak: 'water',
  rain_sensor: 'rain',
  lightning_sensor: 'lightning',
  vibration_sensor: 'vibration',
  weather_station: 'weather',
  media_player: 'media',
  tv: 'media',
  speaker: 'speaker',
  scene: 'scene',
  pico_remote: 'remote',
  keypad: 'remote',
  vcrx: 'remote',
  remote: 'remote',
  timer: 'timer',
  counter: 'timer',
  bridge: 'hub',
  gateway: 'hub',
  zwave: 'hub',
  hub: 'hub',
};

/**
 * A user's own rule: this name gets that mark (§11.2).
 *
 * Ordered, first match wins, and matched against the device's *name* by
 * default because that is what a person recognises — "Holiday Lights" is a
 * switch to the bridge and a string of lights to the household.
 */
export interface IconRule {
  /** A regular expression, as the user typed it. */
  match: string;
  /** A mark name. An unknown one falls through to the derived answer. */
  icon: string;
  /** What to match against. The name, unless said otherwise. */
  on?: 'name' | 'area' | 'type';
}

/**
 * The rules in force.
 *
 * Module state, deliberately, and it is the one place this client keeps any.
 * The alternative is threading a resolver through every widget that draws a
 * mark, and the cost of that is not the plumbing — it is that a third-party
 * widget calling `iconFor` would silently ignore the user's rules unless its
 * author remembered to ask for them. A house has one set of icon rules the way
 * it has one skin.
 */
let rules: IconRule[] = [];

/** Set by the host, from wherever it keeps user content. */
export function setIconRules(next: readonly IconRule[]): void {
  rules = [...next];
}

export function iconRules(): IconRule[] {
  return [...rules];
}

/** What a rule looks at on a device. */
function subject(
  d: { name?: string; ui_hint?: string; device_type?: string; area?: string | null } | undefined,
  on: IconRule['on'],
): string {
  if (on === 'area') return d?.area ?? '';
  if (on === 'type') return d?.ui_hint ?? d?.device_type ?? '';
  return d?.name ?? '';
}

/**
 * The first rule that matches, if any.
 *
 * A malformed pattern matches nothing rather than throwing: these are typed by
 * a person into a text field, and a half-finished regex must not take the page
 * down between keystrokes.
 */
export function ruleFor(
  d: { name?: string; ui_hint?: string; device_type?: string; area?: string | null } | undefined,
  list: readonly IconRule[] = rules,
): IconRule | undefined {
  for (const rule of list) {
    if (typeof rule?.match !== 'string' || rule.match === '') continue;
    try {
      if (new RegExp(rule.match, 'i').test(subject(d, rule.on))) return rule;
    } catch {
      // Not a pattern yet. The next one might be.
    }
  }
  return undefined;
}

/**
 * The mark for a device: the user's rule, then `ui_hint`, then `device_type`.
 *
 * §11.2's order. A rule wins because it is the most specific thing anybody
 * said — the household knows which switch is a fan and the bridge does not.
 */
export function iconFor(
  d: { name?: string; ui_hint?: string; device_type?: string; area?: string | null } | undefined,
): string {
  const named = ruleFor(d)?.icon;
  if (named !== undefined && named in MARKS) return named;

  const hint = d?.ui_hint;
  const type = d?.device_type;
  return (
    (hint !== undefined ? BY_WORD[hint] : undefined) ??
    (type !== undefined ? BY_WORD[type] : undefined) ??
    // A type nobody has drawn for still gets a mark that says "a device", which
    // is true, rather than a bulb, which would not be.
    'device'
  );
}

/**
 * One mark, sized by the box it is given, filled when the thing is on.
 *
 * **The paint is stated here and not by the caller.** Every call site used to
 * carry `fill: none; stroke: currentColor; stroke-width: 1.6` in its own CSS,
 * which was right for strokes on a 24 grid and is wrong for these — and a
 * family that can only be swapped by editing ten stylesheets is a family
 * nobody swaps. The mark owns how it is painted; the caller owns how big it is
 * and what colour `currentColor` resolves to. Inline, because a stylesheet
 * rule in the caller's shadow root would otherwise win.
 *
 * `on` reaches for the filled twin where there is one and is ignored where
 * there is not, so a caller may always pass what it knows.
 */
export function icon(name: string, on = false): TemplateResult {
  const drawn = (on ? FILLED_MARKS[name] : undefined) ?? MARKS[name] ?? MARKS['device'] ?? '';
  return html`<svg
    viewBox="0 0 256 256"
    aria-hidden="true"
    part="icon"
    style="fill:currentColor;stroke:none"
  >
    ${unsafeSVG(drawn)}
  </svg>`;
}

/** Exported so a test can pin that every mapped word has a mark. */
export function markNames(): string[] {
  return Object.keys(MARKS);
}

export function mappedWords(): Record<string, string> {
  return { ...BY_WORD };
}

/**
 * The metric colour a mark belongs to, where one applies.
 *
 * A row of grey icons reads as a form; a thermometer in the temperature tint
 * and a droplet in the humidity one reads as instruments. The tokens are the
 * skin's (§15), so this follows a skin change like everything else — and a mark
 * with no metric gets none rather than an invented colour.
 */
const METRIC: Record<string, string> = {
  temperature: '--hc-metric-temperature',
  water: '--hc-metric-humidity',
  rain: '--hc-metric-humidity',
  weather: '--hc-metric-reading',
  lightning: '--hc-metric-illuminance',
  motion: '--hc-metric-reading',
  vibration: '--hc-metric-reading',
  battery: '--hc-metric-power',
};

export function metricVar(mark: string): string | undefined {
  return METRIC[mark];
}
